theme: jekyll-theme-slate
title: Activity Meter
description: sweiproject-tg-2b-4
plugins:
  - jemoji
avatar: "https://github.com/sweIhm/sweiproject-tg2b-4/blob/master/src/main/resources/static/logo.png"
